### ISSUE TITLE
Blog does not load in Safari

### ISSUE THREAD

**Issue by calebissharp** [TwoStoryRobot/twostoryrobot.com#115]
Safari (and potentially other browsers) doesn't seem to support the API we're using to watch for dark mode changes (`'window.matchMedia("(prefers-color-scheme: dark)").addEventListener' is undefined`). We should add a check to make sure the site still loads properly.

**Comment by jonotron** [comment]
This is high priority as it does not load in iOS. Please define a fix timeline.

**Comment by calebissharp** [comment]
@jonotron Sorry, I though I had pushed this along with #116. I've opened #117 with the fix.
