### ISSUE TITLE
Upgrade to the latest version of Gatsby

### ISSUE THREAD

**Issue by calebissharp** [TwoStoryRobot/twostoryrobot.com#64]
We're using Gatsby v1 but v2 is stable now. Most plugins have been updated to only support v2, so any new plugins we use would have to be an older version. I ran into this when trying to install the styled-components plugin.

**Comment by chrisfosterelli** [comment]
@okanji This is in "Done", but still open. What is the status on this one?

**Comment by okanji** [comment]
We decided to put it on hold, I should have moved it no not doing. I will do that now, thanks for pointing it out.

**Comment by chrisfosterelli** [comment]
@okanji Thanks! Since it's now in Not Doing, we'll want to close it too.

**Comment by okanji** [comment]
Thanks Chris
