### ISSUE TITLE
contact us form is not clearly found

### ISSUE THREAD

**Issue by jonotron** [TwoStoryRobot/twostoryrobot.com#89]
A client called me on the phone wanting to know how to contact us... he had scrolled down to the bottom of the page and just saw the newsletter signup form. It wasn't apparent to him where the contact form was.

I believe we could make our contact CTA more obvious (and likely is more important anyways than the signup to our newsletter CTA)

**Comment by chadfawcett** [comment]
The site doesn't have a contact form. There is just the email address and phone number.

**Comment by jonotron** [comment]
Oh right. Hmmm... now that conversation I had with the potential client seems confusing.

**Comment by chrisfosterelli** [comment]
FWIW a more clear CTA might not be a bad idea anyway though, even if it's just a button with a `mailto:` link. Maybe a topic for the redesign though.
